subtitle: CHANGEME
date: \today
author: Matthew Toohey
geometry:
  - a4paper
  - margin=2cm
mainfont: "IBM Plex Sans Text"
monofont: "JetBrainsMono Nerd Font"
colorlinks: true
linestretch: 1.25
header-includes: |
  \usepackage{float}
  \let\origfigure\figure
  \let\endorigfigure\endfigure
  \renewenvironment{figure}[1][2] {
      \expandafter\origfigure\expandafter[H]
  } {
      \endorigfigure
  }
  \usepackage{mdframed}
  \newcommand{\N}{\mathbb{N}}
  \newcommand{\Z}{\mathbb{Z}}
  \newcommand{\Q}{\mathbb{Q}}
  \newcommand{\R}{\mathbb{R}}
  \newcommand{\C}{\mathbb{C}}
  \newcommand{\larr}{\leftarrow}
  \newcommand{\rarr}{\rightarrow}
  \newcommand{\lrarr}{\leftrightarrow}
  \newcommand{\Larr}{\Leftarrow}
  \newcommand{\Rarr}{\Rightarrow}
  \newcommand{\Lrarr}{\Leftrightarrow}
  \newcommand{\sube}{\subseteq}
  \newcommand{\supe}{\supseteq}
  \newcommand{\sub}{\subset}
  \newmdenv[rightline=false,bottomline=false,topline=false,linewidth=2pt,skipabove=\parskip]{customblockquote}
  \renewenvironment{quote}{\begin{customblockquote}\list{}{\rightmargin=0em\leftmargin=0em}%
  \item\relax\ignorespaces}{\unskip\unskip\endlist\end{customblockquote}}
  \usepackage{multicol}
  \allowdisplaybreaks
