[language-server.efm-langserver]
command = "efm-langserver"

[[language-server.efm-langserver.config.languages.markdown]]
lintCommand = "cspell --config .cspell.yaml lint stdin://${INPUT} --no-progress --no-summary"
lintStdin = true
lintFormats = ["%f:%l:%c - %m"]

[[language]]
name = "markdown"
language-servers = ["efm-langserver"]
