[language-server.diagnostic-ls]
command = "diagnostic-languageserver"
args = ["--stdio"]

[language-server.diagnostic-ls.config.linters.cspell]
sourceName = "cspell"
command = "cspell"
args = [
  "--config",
  ".cspell.yaml",
  "lint",
  "stdin://%filepath",
  "--no-progress",
  "--no-summary",
]
rootPatterns = [".cspell.yaml"]
formatPattern = [".*:(\\d+):(\\d+) - (.*)", { line = 1, column = 2, message = 3 }]

[language-server.diagnostic-ls.config.filetypes]
markdown = "cspell"

[[language]]
name = "markdown"
language-servers = ["diagnostic-ls"]

[[language]]
name = "rmarkdown"
language-id = "rmd"
