name: "Lint"
on:
  push:
    branches: ["**"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache nix
        uses: mtoohey31/cache-flake-attrs@v2
        with:
          key: ${{ runner.os }}-nix-${{ hashFiles('./flake.lock', './nix/flake.lock', './nix/flake.nix') }}
          flake_paths: ./nix#devShells.x86_64-linux.default
      - name: Lint
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --no-write-lock-file ./nix# -ic make -f ci.mk
